---
title: "Clustering Seattle Data"
output: Jasmine Duong G6
---
Collect the data we prepared in Python:

```{r collecting, eval=TRUE}
link='https://github.com/Group-6-542/EmilyRepository/raw/main/mergedGroupDataFinal.csv'

finalData=read.csv(link)
```


## Preparing data:

```{r, eval=TRUE}

dfClus=finalData[,-1]
summary(dfClus)
```


## Rescale the units in the data 
```{r, eval=TRUE}
dfClus=scale(dfClus)

summary(dfClus)

```


## renaming the metrix
```{r clusRename, eval=TRUE}
row.names(dfClus)=finalData$zipcode
head(dfClus)
```



```{r clusSeed, eval=TRUE}
set.seed(999) # this is for replicability of results
```



```{r clusDistance, eval=TRUE}
library(cluster)
dfClus_D=cluster::daisy(x=dfClus)
```


## Partitioning technique
```{r clusPam, eval=TRUE}
NumCluster=4
res.pam = pam(x=dfClus_D,
              k = NumCluster,
              cluster.only = F)
```


### 2. Clustering results. 
```{r cluspamSave, eval=TRUE}
finalData$pam=as.factor(res.pam$clustering)
```


```{r cluspamquery1, eval=TRUE}
finalData[finalData$pam==1,'zipcode']
```



```{r cluspamquery2, eval=TRUE}
finalData[finalData$zipcode==98105,'pam']
```



```{r cluspamREPORTtable, eval=TRUE}
table(finalData$pam)
```


### 3. Evaluate Results
```{r cluspamREPORT_silave, eval=TRUE}
library(factoextra)
fviz_silhouette(res.pam)
```


```{r cluspamREPORT_datasil, eval=TRUE}
pamEval=data.frame(res.pam$silinfo$widths)
head(pamEval)
```


```{r cluspamREPORT_silnegative, eval=TRUE}
pamEval[pamEval$sil_width<0,]
```


##Factoring

```{r}
subSet = finalData [,c(4:6)]
```

```{r}
names(subSet)
```
```{r}
install.packages("lavaan", dependencies = TRUE)
```

```{r}
library(lavaan)
```

```{r}
model='dem=~ avgAGI + casesReported + numberOfPets'

fit<-cfa(model, data = subSet,std.lv=TRUE)
indexCFA=lavPredict(fit)
```

```{r}
library(magrittr)
```

```{r}
indexCFA%>%head(10)
```


```{r}
library(scales)
indexCFANorm=rescale(as.vector(indexCFA), to = c(0, 10))
```


```{r}
finalData$Factoring=indexCFANorm
```

```{r}
library(ggplot2)
```

```{r}
base=ggplot(data= finalData, aes(x=Factoring))
base+geom_histogram()
```

```{r}
base=ggplot(data= finalData, aes(x=Factoring, y=avgAGI))
base+geom_point()
```
```{r}
base=ggplot(data= finalData, aes(x=Factoring, y=casesReported))
base+geom_point()
```

```{r}
base=ggplot(data= finalData, aes(x=Factoring, y=numberOfPets))
base+geom_point()
```

```{r}
evalCFA1=parameterEstimates(fit, standardized =TRUE)
```

```{r}
evalCFA1[evalCFA1$op=="=~",c('rhs','std.all','pvalue')]
```

```{r}
evalCFA2=as.list(fitMeasures(fit))
```

##HMMMMMMMMMMMMMMM
```{r}
evalCFA2[c("chisq", "df", "pvalue")] 
```
```{r}
evalCFA2$tli
```
```{r}
evalCFA2[c( 'rmsea.ci.lower','rmsea','rmsea.ci.upper')] 
```
```{r}
install.packages("semPlot5", dependencies = TRUE)
```


```{r}
library(semPlot)
```

```{r}
semPaths(fit, what='std', nCharNodes=10, sizeMan=8,
         edge.label.cex=1.5, fade=T,residuals = F)
```

